# Generated by Django 3.2.12 on 2023-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.UUIDField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('low', 'low'), ('high', 'high')], default='low', max_length=10)),
                ('incidentType', models.CharField(choices=[('landslide', 'landslide'), ('temperature', 'temperature')], default='temperature', max_length=20)),
                ('measurement', models.DecimalField(decimal_places=10, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
