# Generated by Django 3.2.12 on 2023-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('normal', 'normal'), ('low', 'low'), ('high', 'high')], default='normal', max_length=10)),
                ('incidentType', models.CharField(max_length=100)),
                ('measurement', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('date', models.DateField(default=True)),
            ],
        ),
    ]
