# Generated by Django 3.2.12 on 2023-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentType',
            field=models.CharField(choices=[('landslide', 'landslide'), ('temperature', 'temperature')], default='temperature', max_length=20),
        ),
    ]
