# Generated by Django 3.2.12 on 2023-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_auto_20230208_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incidentId',
            new_name='id',
        ),
    ]
